version: "3.9"
services:
  app:
    build: .
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://user:password@db:5432/devdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devdb
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        until pg_isready -h db -p 5432 -U user; do
          >&2 echo 'Waiting for PostgreSQL to become available...'
          sleep 1
        done
        echo 'PostgreSQL is available'
        PGPASSWORD=password psql -h db -U user -d devdb -f migrations/create_users_table.sql
        npm run dev
      "

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devdb
    volumes:
      - user-armazenados-dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d devdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  user-armazenados-dev:
